### ISSUE TITLE
switch to slf4j for logging

### ISSUE THREAD

**Issue by pjfanning** [LucaCanali/sparkMeasure#1]
[SLF4J](https://www.slf4j.org/manual.html) is a nice logging abstraction that allows developers include logging but lets users choose their preferred logging framework.
Could you switch to having a compile dependency on slf4j-api jar and a test dependency on log4j and the [log4j-slf4j-impl](https://logging.apache.org/log4j/2.0/log4j-slf4j-impl/index.html)?

**Comment by LucaCanali** [comment]
Thanks for the PR.

**Comment by pjfanning** [comment]
Thanks for merging
