### ISSUE TITLE
Error creating a TaskMetrics dataframe

### ISSUE THREAD

**Issue by franciscojfs** [LucaCanali/sparkMeasure#12]
Hello!

I'm trying to create a dataframe to save my task metrics in Hive. However, when I call the create_taskmetrics_DF method, as below, the error occurs on the print screen.

`tm = taskmetrics.create_taskmetrics_DF("PerfTaskMetrics")`

![image](https://user-images.githubusercontent.com/30843274/43734775-315dee7e-998f-11e8-9150-c98c13044533.png)

It looks like an error in the class, looking only at the error message.

**Comment by LucaCanali** [comment]
Thanks @franciscojfs for reporting this. I have just pushed a fix for it, let me know if it works for you now.

**Comment by franciscojfs** [comment]
I made a correction in the code and opened a pull request to integrate that on your code, if you don't mind. I hope that be useful!

Thank you for your kick response :)
