### ISSUE TITLE
jupyter notebook example missing

### ISSUE THREAD

**Issue by catch93** [LucaCanali/sparkMeasure#19]
I am wondering if you still have a sample of jupyter notebook with sparkmeasure
The following SparkMeasure_Jupyer_Python_getting_started.ipynb is not found as of today
Thanks in advance

**Comment by LucaCanali** [comment]
Hi, 
there are a couple of example notebooks in https://github.com/LucaCanali/sparkMeasure/blob/master/examples 
Regards,
Luca
