### ISSUE TITLE
How to get the execution time for EACH operator in Spark SQL?

### ISSUE THREAD

**Issue by niewangwen** [LucaCanali/sparkMeasure#35]
Execuse me, I'm having some problem when getting the execution time of each operator in Spark SQL. For example, I'm using the belowed sql to test:   
"select count(*) from range(1000) cross join range(1000) cross join range(1000)"
and I found some details in the Spark Web UI like this:
![4](https://user-images.githubusercontent.com/41497436/137691800-7be2d5cb-a74f-4b84-9190-663b5e26c545.png)
I wish to get the execution time of every operator, but operators like "RANGE, PROJECT etc" doesn't have the corresponding metrics.
I look into the log and I find that those operator doesn't have any metrics, so maybe this is the reason.
But I want to get execution time for each operator, how can I do that?

**Comment by LucaCanali** [comment]
Hi, 
I agree that would be useful, but I am afraid Spark does not instrument each operator with time.
