### ISSUE TITLE
Peak Memory usage - PySpark 3 on Azure Synapse

### ISSUE THREAD

**Issue by jacwalte** [LucaCanali/sparkMeasure#40]
Found an odd issue.  We recently started running our jobs through Azure Synapse.  While using Azure HDI, we were able to record the peakExecutionMemory, but for some reason with Azure Synapse, all the values are 0.

We are using TaskMetrics to get the most information out of the run and within the csv generated, other columns are populated except for the peakExecutionMemory which are all 0.

Is this a known issue?

We are running with python 3.7, pyspark 3.2.1, and scala 2.12 and using the spark-measure_2.12:0.18.jar

**Comment by jacwalte** [comment]
Looks to have been another issue - peak memory is now being reported - Thanks!

**Comment by LucaCanali** [comment]
Good to know this works OK for you.
Cheers, Luca
