### ISSUE TITLE
can't find spark-measure 0.21

### ISSUE THREAD

**Issue by hen-shalom-riski** [LucaCanali/sparkMeasure#43]
when try to compile the testsparkmeasurescala_2.12

`not found: https://repo1.maven.org/maven2/ch/cern/sparkmeasure/spark-measure_2.12/0.21/spark-measure_2.12-0.21.pom`

**Comment by LucaCanali** [comment]
I confirm that this is an annoying issue, somehow the pom file did not get to maven repos for version 0.21.
There does not seem to be a foundamental reason for that, so I'll probably push version 0.22 to work around that.
In the meantime, if you need the pom file, you can dowload and compile the latest sparkMeasure vesion from this repo in github or else use vesion 0.20 on maven central.

**Comment by LucaCanali** [comment]
This is now fixed in sparMeasure v0.22
See: https://repo1.maven.org/maven2/ch/cern/sparkmeasure/spark-measure_2.12/0.22/spark-measure_2.12-0.22.pom
