### ISSUE TITLE
java compatibility

### ISSUE THREAD

**Issue by geofflangenderfer** [LucaCanali/sparkMeasure#44]
are there any barriers to using this with a java spark job?

Scala classes are java classes, so I think it should be fine: https://stackoverflow.com/questions/44993014/can-scala-classes-be-used-in-java#:~:text=Scala%20classes%20are%20Java%20classes,in%20Java%2C%20for%20example%20traits.

I'll report back

**Comment by LucaCanali** [comment]
INdeed this should work with java too.
