### ISSUE TITLE
'JavaPackage' object is not callable when using the Colab Example

### ISSUE THREAD

**Issue by ssalloum** [LucaCanali/sparkMeasure#50]
Hello,
I am trying the Google Colab example. I get 

> TypeError: 'JavaPackage' object is not callable

 when running: 
`stagemetrics = StageMetrics(spark)`

Are there any other settings to do with Google Colab?
Thank you!

**Comment by LucaCanali** [comment]
The Colab example should work OK, I have just tested it.
Can you please try again and let me know if you still have issues?
Best,
Luca

**Comment by ssalloum** [comment]
Hello, 
I tested it again. It is working without any errors. 
I have no idea why I got that error before. 
Thank you!
Salman

**Comment by LucaCanali** [comment]
Good to know, thanks for the update.
