### ISSUE TITLE
Feature Request: Support Prometheus Gateway Sink in Flight Recorder Mode

### ISSUE THREAD

**Issue by kiranatlu** [LucaCanali/sparkMeasure#54]
Implement a prometheus sink in in Flight Recorder Mode that formats metrics into a Prometheus-friendly format and pushes them to a configured Prometheus Pushgateway endpoint.

`sparkmeasure` currently offers Prometheus sink capabilities, facilitating the monitoring of Spark performance metrics within Prometheus ecosystems. Extending this functionality to include support for Flight Recorder Mode represents a significant enhancement. This feature would enable users to push metrics directly to a Prometheus Pushgateway endpoint.

**Comment by LucaCanali** [comment]
A first version of Prometheus Gateway Sink in Flight Recorder Mode at:
https://github.com/LucaCanali/sparkMeasure/commit/4d8743c0da2030038a76c3ee756e4c65585b9cbc
