### ISSUE TITLE
AttributeError: 'StageMetrics' object has no attribute 'stagemetrics'

### ISSUE THREAD

**Issue by cometta** [LucaCanali/sparkMeasure#56]
i get above error when run the TPC example 

```
results = tpcds.run_TPCDS()
```

**Comment by LucaCanali** [comment]
Hi,

The examples related to running sparkMeasure with TPCDS workload can be found at https://github.com/LucaCanali/Miscellaneous/tree/master/Performance_Testing/TPCDS_PySpark
They seem to work fine for me.
Can you please check and in case provide more details?

Best,
Luca
