### ISSUE TITLE
Getting Spark Task related metrics using Prometheus Push Gateway

### ISSUE THREAD

**Issue by krishhkk** [LucaCanali/sparkMeasure#57]
Hi, 

I am able to see the stage related metrics exposed to prometheus using push gateway sink. But, I am not seeing any Task related metrics. 
1. Is Task related metrics are supported by prometheus push gateway sink ?
2. If supported, is there a separate configuration to expose Task metrics ?

**Comment by LucaCanali** [comment]
Hi @krishhkk 
I am glad to hear that the Prometheus Pushgateway sink works for you.
Currently it collects Stage-level metrics only. I have just updated the documentation to make this explicit: [Prometheus Pushgateway sink doc](https://github.com/LucaCanali/sparkMeasure/blob/master/docs/Flight_recorder_mode_PrometheusPushgatewaySink.md)
