### ISSUE TITLE
enable travis-ci

### ISSUE THREAD

**Issue by pjfanning** [LucaCanali/sparkMeasure#6]
@LucaCanali would it be possible for you to login to Travis CI with your github credentials and enable Travis builds for sparkMeasure?

You could then add these badges at the top of your README.md.
These are copied from https://github.com/swagger-akka-http/swagger-akka-http/blob/master/README.md

```
[![Build Status](https://travis-ci.org/LucaCanali/sparkMeasure.svg?branch=master)](https://travis-ci.org/LucaCanali/sparkMeasure)
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/LucaCanali/sparkMeasure/badge.svg)](https://maven-badges.herokuapp.com/maven-central/LucaCanali/sparkMeasure)
```

**Comment by LucaCanali** [comment]
Good idea, thanks. This is now done.
